name: Simple CI

on:
  push:
    branches: [ "main" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Exibir mensagem
        run: echo "GitHub Actions está funcionando 🚀"
